### PR TITLE
Enhanced game screen

### LINKED ISSUE #53: Android application testing
**User story:** As a player, I want the application to perform according to advertised functions, so I will not be disappointed when playing the game.

**Acceptance criteria:**
* each application screen to have a few UI tests to check the functionalities of their elements.

### LINKED ISSUE #57: Enhanced game UI
**User story:** As a player, I want the user interface of the game to include some data of the state of the game, so I can play accordingly.

**Acceptance criteria:**
- the "game" screen shall display a game over message when the tank's health points drop to zero,
- the "game" screen shall display the current health of the player's tank,
- the "game" screen shall display the cooldown of the "shoot" button, and
- the "game" screen may have other minor improvements.

### LINKED ISSUE #59: Game screen orientation change bug
Changing the application orientation while on the game screen makes the app reconnect to token assignment, making the player lose connection to whichever tank they were connected to.

### LINKED ISSUE #63: Disabling tank
**User story:** As a player, I want the enemy tank to become inactive once its health points reach 0 so that I can emerge victorious.

**Acceptance criteria:**
* a tank with health points equal to 0 shall not move.
* a tank with health points equal to 0 shall not shoot.
* the app shall stop transmitting the camera feed of the tank when its health points are equal to 0.

### LINKED ISSUE #65: Enhanced user experience
**User story:** As a player, I want the design of the game be pleasant and provide feedback when navigating to different screens and pressing buttons so that I have a good experience playing the game

**Acceptance criteria:**
* when a player presses a button there is a ripple effect to let the player know the button has actually been pressed
*  the exit-button from main menu screen and game screen are customized to fit the design of the game
* the font of the game is in military style

### PR DESCRIPTION
**Pull request by BaoLindgren**
The enhanced game screen adds the following to the basic game screen:
- a health bar displaying the health of the player's tank,
- a game over message that gets displayed when the health of the player's tank drops to 0, and
- a cool down animation for the shoot to indicate when the player can shoot.

Additionally, commit 0ecb0fc9a2f27eb5937879f32db7be7378974fef fixes a bug where the connection is lost when changing the orientation of the application in the middle of a game.

Closes #53 
Closes #57 
Closes #63 
Closes #65 
Fixes #59 

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by BaoLindgren** [comment]
Changes to the Android CI to match the current app layout are on their way

**Comment by BaoLindgren** [comment]
Android CI and structure has been updated and match each other. Furthermore, other screens have also been enhanced through the screen-refinement branch

**Comment by Quinstedt** [comment]
image
 Do this and it will pass, you are making sure that the test is ignore by CI.
 
 Try to break down the test into smaller part or do this, 
 
Keep the  @LargeTest and a @Test  comment the @Test and uncommented when you  which makes the CI to ignore that test. And modify the DoD.
And you can add an extra check in the DoD. You can see the last line there, you use
to break the line
https://github.com/DIT113-V22/group-08/blob/master/.github/dod.yaml

Easier fix and the you dont need to delete your test.

**Comment by Quinstedt** [comment]
EXACTLY HERE IS YOUR BUG!

image

image

**Comment by AeroStun** [comment]
Please don't link my (especially full) name with my nickname. Thanks you for your understanding and your future effort in complying with my privacy request.

**Comment by Operatik** [comment]
All CIs has completed process and passed, as detailed in the criteria. Android UI has improved for QoL changes
but also privacy issues has been solved.

Merge approved.

**Review by Operatik — APPROVED** [review]
All CIs has completed process and passed, as detailed in the criteria. Android UI behavior has improved for QoL and changes but also privacy concerns have been solved. Testing are working as intended.

Merge approved.

**Pull request merged**
