### PR TITLE
Game screen prototype modifications

### PR DESCRIPTION
**Pull request by khaledad**
**Added compare to the previous version:**
* joystick
* shoot button
* exit button

Also color palette changed to match chosen theme "Moon".

Related issue: #4

### CODE REVIEW

**Comment by litvem** [comment]
Code reviewed. Approved for merge. Well done!

**Comment by khaledad** [comment]
Thank you

**Review by LuizRosane — COMMENTED** [review]
The video stream is displayed correctly and the required buttons are also present.

**Review by LuizRosane — APPROVED** [review]
All components are working as required

**Pull request merged**
